<?php

namespace Database\Seeders;

use App\Models\EmployeeDepartment;
use Illuminate\Database\Seeder;

class EmployeeDepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pemeliharaan I';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Perencanaan & Penerimaan Barang/Jasa';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Corporate Social Responsibility';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Administrasi Pemasaran';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Bengkel & Fabrikasi';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pemeliharaan II';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Produksi I A';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Teknik & Bisnis';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pemeliharaan III';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pengelolaan Pelabuhan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pengadaan Barang';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Keamanan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Administrasi & Penjualan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Reliability';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Proses & Pengendalian Kualitas';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Produksi III A';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Produksi III B';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pelayanan Umum';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Keselamatan & Kesehatan Kerja';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Produksi I B';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Perencanaan Strategi Pemeliharaan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Keuangan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Anggaran';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Perencanaan Produksi & Pengelolaan Energi';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Audit Keuangan & Umum';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Rancang Bangun';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pelaporan Keuangan & Manajemen';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Produksi II A';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Produksi II B';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Perencanaan & Pengendalian TA';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pengelolaan Mitra Produksi';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Akuntansi Biaya';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pengadaan Jasa';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Inspeksi Teknik';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Inovasi & Sistem Manajemen';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Pengembangan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Project Customer Centric Model';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Remunerasi & Hubungan Industrial';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pengembangan & Organisasi';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Riset';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Hukum & Sekretariat';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep TKP & Manajemen Risiko';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Project Agrosolution';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Komunikasi Korporat';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Lingkungan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Yayasan Petrokimia Gresik';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Audit Operasi & Produksi';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Mitra Bisnis';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Direktorat Utama';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Pabrik I';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Satuan Pengawasan Intern';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'DPB. Anak Perusahaan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Transformasi Bisnis';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Umum';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Staf Komp. Pengembangan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Perencanaan & Pengendalian Pemeliharaan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Pabrik II';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Sekretaris Perusahaan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Administrasi Keuangan';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Teknik';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Pengembangan Korporat';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Dep Portofolio Bisnis';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Teknologi';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Staf Dit. Operasi dan Produksi';
        $ed->save();
        $ed = new EmployeeDepartment();
        $ed->name = 'Komp Pabrik III';
        $ed->save();
    }
}
